version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
          