name: 部署(Deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 使用 git 检出仓库
        uses: actions/checkout@v7
      - name: 设置 Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: 安装&构建
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm run build
      - name: 上传 artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./dist/"
          include-hidden-files: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5